services:
  refrain:
    build: .
    image: gerald-lbn/refrain
    container_name: refrain
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /home/gerald/Music:/music:ro
      - ./.volumes/refrain/config:/config
